version: "3.9"

services:
  db:
    image: "mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=zay
    volumes:
      - cl_db:/var/lib/mysql

volumes:
  cl_db:
    driver: local
