version: "3.9"

services:
  web:
    image: franno0/cl-frontend:v1.0
    ports:
      - 5173:5173
    depends_on:
      - db
  backend:
    image: franno0/cl-backend:v1.0
    ports:
      - 3000:3000
    environment:
      - DB_USERNAME=root
      - DB_PASSWORD=root1234
      - DB_DATABASE=cl_eksamen
    depends_on:
      - db
  db:
    image: "mysql"
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_DATABASE=cl_eksamen
    volumes:
      - cl_db:/var/lib/mysql

volumes:
  cl_db:
    driver: local
