FROM node:22-alpine

WORKDIR /app

COPY package.json .

RUN npm install

COPY . .

ENV DB_USERNAME=root
ENV DB_PASSWORD=root1234
ENV DB_DATABASE=cl_eksamen

RUN npm run db:reset

EXPOSE 3000

CMD ["npm", "run", "start"]
